- name: Command vs Shell
  hosts: localhost
  tasks:
  - name: to run and redirect in command module
    ansible.builtin.command: "echo 'Hi, this from command module' > /tmp/command.txt"
  - name: to run and redirect in command module
    ansible.builtin.command: "echo 'Hi, this from shell module' > /tmp/shell.txt"