- name: to configure frontend
  hosts: frontend
  become: yes
  tasks:
  - name: Install Nginx
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start and enable Nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: Recursively remove directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent
  
  # - name: download backend code
  #   ansible.builtin.get_url:
  #    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
  #    dest:  /tmp/frontend.zip

  # - name: Extract backend.zip  into /app
  #   ansible.builtin.unarchive:
  #     src: /tmp/frontend.zip
  #     dest: /usr/share/nginx/html
  #     remote_src: yes

  #   - name: Copy backend service
  #   ansible.builtin.copy:
  #     src: frontend.service
  #     dest: /etc/nginx/default.d/expense.conf